import pytest
from unittest.mock import MagicMock, patch
from detection.llm_signal import classify_with_llm, LLMResult


def _make_mock_response(content: str):
    mock = MagicMock()
    mock.choices[0].message.content = content
    return mock


def test_returns_llm_result_type():
    with patch("detection.llm_signal.client.chat.completions.create",
               return_value=_make_mock_response("0.15")):
        result = classify_with_llm("Once upon a time in a small village...")
        assert isinstance(result, LLMResult)


def test_parses_score_correctly():
    with patch("detection.llm_signal.client.chat.completions.create",
               return_value=_make_mock_response("0.87")):
        result = classify_with_llm("This content was generated by an AI system.")
        assert abs(result.score - 0.87) < 0.01


def test_clamps_score_above_1():
    with patch("detection.llm_signal.client.chat.completions.create",
               return_value=_make_mock_response("1.5")):
        result = classify_with_llm("some text")
        assert result.score == 1.0


def test_clamps_score_below_0():
    with patch("detection.llm_signal.client.chat.completions.create",
               return_value=_make_mock_response("-0.3")):
        result = classify_with_llm("some text")
        assert result.score == 0.0


def test_unparseable_response_returns_uncertain():
    with patch("detection.llm_signal.client.chat.completions.create",
               return_value=_make_mock_response("I cannot determine this.")):
        result = classify_with_llm("some text")
        assert result.score == 0.5
        assert result.parse_error is True


def test_api_error_returns_uncertain():
    with patch("detection.llm_signal.client.chat.completions.create",
               side_effect=Exception("API error")):
        result = classify_with_llm("some text")
        assert result.score == 0.5
        assert result.api_error is True
