from dataclasses import dataclass, field
from groq import Groq
from config import GROQ_API_KEY, GROQ_MODEL

client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = """You are an expert at detecting whether text was written by a human or generated by AI.
Analyze the submitted text and return ONLY a single decimal number between 0.0 and 1.0, where:
- 0.0 = you are certain the text is human-written
- 1.0 = you are certain the text is AI-generated
- 0.5 = you cannot determine

Return only the number. No explanation. Example: 0.12"""


@dataclass
class LLMResult:
    score: float
    raw_response: str = ""
    parse_error: bool = False
    api_error: bool = False


def classify_with_llm(text: str) -> LLMResult:
    """Send text to Groq LLM and return AI-likelihood score 0–1."""
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.1,
            max_tokens=10,
        )
        raw = response.choices[0].message.content.strip()
        return _parse_score(raw)
    except Exception:
        return LLMResult(score=0.5, api_error=True)


def _parse_score(raw: str) -> LLMResult:
    try:
        score = float(raw)
        score = max(0.0, min(1.0, score))
        return LLMResult(score=round(score, 4), raw_response=raw)
    except ValueError:
        return LLMResult(score=0.5, raw_response=raw, parse_error=True)
